version: '3.2'

services:

  frontend:
    container_name: rebb_front
    build: frontend
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  backend:
    container_name: rebb_back
    build: backend
    ports:
      - 21080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  db:
    image: mysql:8
    container_name: rebb_db
    environment:
      - MYSQL_ROOT_PASSWORD=rebbrules
      - MYSQL_DATABASE=rebb
      - MYSQL_USER=rebb
      - MYSQL_PASSWORD=rebbuser

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: rebb_myadminp
    ports:
      - 8000:80
  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret